[project]
name = "quicktemplate"
version = "0.1.0"
description = "Python quick  start template"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.0",
    "polars>=1.22.0",
    "pre-commit>=4.1.0",
]
