[tool.poetry]
name = "QuickTemplate"
description = ""
authors = ["Michael Verdegaal"]
repository = "https://github.com/growficient/QuickTemplate
version = "1.0.0"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.12,<3.13"

[tool.black]
line-length = 100
extend-exclude = '/^[^.]+$|\.(?!(py)$)([^.]+$)/'

[tool.isort]
profile = "black"
line_length = 100

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"
